# Generated by Django 4.2.9 on 2024-05-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogpost',
            table='blog_post',
        ),
    ]
